CREATE DATABASE QUAN_LY_BAN_VE_MAY_BAY;
USE QUAN_LY_BAN_VE_MAY_BAY;
----------------------------------------------------------------------
--MODULE 1: QUẢN LÝ NGƯỜI DÙNG (GỒM BẢNG KHÁCH HÀNG VÀ BẢNG NHÂN VIÊN)
--BẢNG KHÁCH HÀNG: 
CREATE TABLE KHACH_HANG (
	MA_KH VARCHAR(10) PRIMARY KEY NOT NULL,
	TEN_KH NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) UNIQUE,
	SDT_KH VARCHAR(15) UNIQUE,
	DIACHI NVARCHAR(200)
);
--BẢNG NHÂN VIÊN:
CREATE TABLE NHAN_VIEN(
	MA_NV VARCHAR(10) PRIMARY KEY NOT NULL,
	TEN_NV NVARCHAR(100) NOT NULL,
	CHUCVU NVARCHAR(100),
	SDT_NV VARCHAR(15) UNIQUE
);
----------------------------------------------------------------------------------
--MODULE 2: QUẢN LÝ CHUYẾN BAY (GỒM BẢNG HÃNG BAY, MÁY BAY, SÂN BAY VÀ CHUYẾN BAY)
--BẢNG HÃNG BAY:
CREATE TABLE HANG_BAY (
	MA_HANG VARCHAR(10) PRIMARY KEY NOT NULL,
	TEN_HANG NVARCHAR(100) NOT NULL UNIQUE
);
--BẢNG MÁY BAY:
CREATE TABLE MAY_BAY (
	MA_MB VARCHAR(10) PRIMARY KEY NOT NULL,
	MA_HANG VARCHAR(10) REFERENCES HANG_BAY(MA_HANG) NOT NULL,
	TEN_MB NVARCHAR(100)
);
--BẢNG SÂN BAY:
CREATE TABLE SAN_BAY (
	MA_SB VARCHAR(10) PRIMARY KEY NOT NULL,
	TEN_SB NVARCHAR(100) NOT NULL UNIQUE,
	THANH_PHO NVARCHAR(100)
);
--BẢNG CHUYẾN BAY:
CREATE TABLE CHUYEN_BAY (
	MA_CB VARCHAR(10) PRIMARY KEY,
	MA_MB VARCHAR(10),
	SB_DI VARCHAR(10) NOT NULL,
	SB_DEN VARCHAR(10) NOT NULL,
	NGAY_BAY DATETIME,
	FOREIGN KEY (MA_MB) REFERENCES MAY_BAY(MA_MB),
	FOREIGN KEY (SB_DI) REFERENCES SAN_BAY(MA_SB),
	FOREIGN KEY (SB_DEN) REFERENCES SAN_BAY(MA_SB),
	CONSTRAINT CHECK_SAN_BAY CHECK (SB_DI <> SB_DEN)
);
---------------------------------------------------------------------------------------
--MODULE 3: QUẢN LÝ GHẾ & ĐẶT VÉ( GỒM BẢNG GHẾ, BẢNG HẠNG GHẾ, BẢNG VÉ VÀ BẢNG ĐẶT CHỖ)
--BẢNG HẠNG GHẾ:
CREATE TABLE HANG_GHE(
	MA_HANG_GHE VARCHAR(10) PRIMARY KEY,
	TEN_HANG_GHE NVARCHAR(100) NOT NULL
);
--BẢNG GHẾ:
CREATE TABLE GHE(
	MA_GHE VARCHAR(10) PRIMARY KEY,
	MA_HANG_GHE VARCHAR(10),
	SO_GHE VARCHAR(10) NOT NULL,
	FOREIGN KEY (MA_HANG_GHE) REFERENCES HANG_GHE(MA_HANG_GHE),
	CONSTRAINT UQ_GHE UNIQUE (MA_HANG_GHE, SO_GHE)
);
--BẢNG VÉ:
CREATE TABLE VE(
	MA_VE VARCHAR(10) PRIMARY KEY,
	MA_KH VARCHAR(10) NOT NULL,
	MA_CB VARCHAR(10) NOT NULL,
	MA_GHE VARCHAR(10) NOT NULL,
	MA_HOA_DON VARCHAR(10),
	NGAY_MUA DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH),
	FOREIGN KEY (MA_CB) REFERENCES CHUYEN_BAY(MA_CB),
	FOREIGN KEY (MA_GHE) REFERENCES GHE(MA_GHE),
	CONSTRAINT UQ_CHUYEN_BAY UNIQUE (MA_CB, MA_GHE) 
);
--BẢNG ĐẶT CHỖ:
CREATE TABLE DAT_CHO(
	MA_DAT_CHO VARCHAR(10) PRIMARY KEY,
	MA_KH VARCHAR(10) NOT NULL,
	MA_CB VARCHAR(10) NOT NULL,
	MA_GHE VARCHAR(10) NOT NULL,
	THOI_GIAN DATETIME DEFAULT CURRENT_TIMESTAMP,
	TRANG_THAI NVARCHAR(50),
	FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH),
	FOREIGN KEY (MA_CB) REFERENCES CHUYEN_BAY(MA_CB),
	FOREIGN KEY (MA_GHE) REFERENCES GHE(MA_GHE),
	CONSTRAINT UQ_DAT_CHO UNIQUE (MA_CB, MA_GHE)
);
-------------------------------------------------------------------------------------------------------------------
--MODULE 4: THANH TOÁN & DỊCH VỤ ( GỒM BẢNG HÓA ĐON, BẢNG THANH TOÁN, BẢNG HÀNH LÝ, BẢNG KHUYẾN MÃI, BẢNG BẢNG GIÁ)
--BẢNG KHUYẾN MÃI:
CREATE TABLE KHUYEN_MAI(
	MA_KM VARCHAR(10) PRIMARY KEY,
	TEN_KM NVARCHAR(100) NOT NULL,
	PHAN_TRAM_GIAM_GIA DECIMAL(5,2),
	NGAY_BD DATETIME,
	NGAY_KT DATETIME,
	CONSTRAINT CHECK_NGAY CHECK (NGAY_KT >= NGAY_BD)
);
--BẢNG HÓA ĐƠN:
CREATE TABLE HOA_DON(
	MA_HOA_DON VARCHAR(10) PRIMARY KEY,
	MA_KM VARCHAR(10),
	NGAY_TAO DATETIME DEFAULT CURRENT_TIMESTAMP,
	TONG_TIEN DECIMAL(15,2),
	FOREIGN KEY (MA_KM) REFERENCES KHUYEN_MAI(MA_KM)
);
--BẢNG THANH TOÁN:
CREATE TABLE THANH_TOAN(
	MA_TT VARCHAR(10) PRIMARY KEY,
	MA_HOA_DON VARCHAR(10) UNIQUE,
	PHUONG_THUC NVARCHAR(50),
	NGAY_THANH_TOAN DATETIME DEFAULT CURRENT_TIMESTAMP,
	SO_TIEN_DA_TRA DECIMAL(15,2),
	FOREIGN KEY (MA_HOA_DON) REFERENCES HOA_DON(MA_HOA_DON)
);
--BẢNG HÀNH LÝ:
CREATE TABLE HANH_LY(
	MA_HL VARCHAR(10) PRIMARY KEY,
	MA_VE VARCHAR(10),
	KHOI_LUONG FLOAT,
	GIA_TIEN DECIMAL(15,2),
	FOREIGN KEY (MA_VE) REFERENCES VE(MA_VE)
);
--BẢNG BẢNG GIÁ:
CREATE TABLE BANG_GIA(
	MA_BG VARCHAR(10) PRIMARY KEY,
	MA_CB VARCHAR(10),
	MA_HANG_GHE VARCHAR(10),
	GIA_TIEN DECIMAL(15,2),
	FOREIGN KEY (MA_CB) REFERENCES CHUYEN_BAY(MA_CB),
	FOREIGN KEY (MA_HANG_GHE) REFERENCES HANG_GHE(MA_HANG_GHE)
);
--THÊM LIÊN KẾT HÓA ĐƠN VÀ VÉ (VÉ - MODULE 3 VÀ HÓA ĐƠN - MODULE 4)
ALTER TABLE VE
ADD CONSTRAINT FK_VE_HOADON FOREIGN KEY (MA_HOA_DON) REFERENCES HOA_DON(MA_HOA_DON);
---------------------------------------------------
--MODULE 5: BÁO CÁO & HỆ THỐNG (GỒM BẢNG AUDIT_LOG)
CREATE TABLE AUDIT_LOG(
	LOG_ID INT PRIMARY KEY,
	HANH_DONG NVARCHAR(50),
	THOI_GIAN_TAO DATETIME DEFAULT CURRENT_TIMESTAMP,
	MO_TA NVARCHAR(200)
);
